### ISSUE TITLE
Add List Name Parameter

### ISSUE THREAD

**Issue by HeyItsGilbert** [potatoqualitee/influx#2]
Using the exodus GH action outputs CSV's that are formatted only for following. If given a type of list, allow a list-name to also be passed. This would allow people to sync their Twitter lists with exodus + influx.

Something like:
```
- name: Import the results
        uses: potatoqualitee/influx@v1
        id: import
        with:
          server: fosstodon.org
          type: list
          list-name: PowerShell Podcast
          file-path: ${{ steps.export.outputs.mastodon-csv-filepath }}
```
