### ISSUE TITLE
Deprecation of "actions/upload-artifact: v3"

### ISSUE THREAD

**Issue by Callidus2000** [potatoqualitee/influx#3]
Hi,
starting today the workflow fails with the error `This request has been automatically failed because it uses a deprecated version of "actions/upload-artifact: v3". Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/`

My workflow config:

```yaml
name: Backup Mastodon Account
on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"
jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Backup Mastodon Account
        uses: potatoqualitee/fossilize@v1
        id: backup
        with:
          server: ruhr.social
        env:
          ACCESS_TOKEN: "${{ secrets.TOKEN }}"
```
